name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 6
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, Win32]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild of plugin dll
      working-directory: XBrackets\
      run: msbuild XBrackets_VC2017.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v142"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v5
      with:
          name: plugin_dll_x64
          path: XBrackets\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\XBrackets.dll

    - name: Archive artifacts for Win32
      if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v5
      with:
          name: plugin_dll_x86
          path: XBrackets\${{ matrix.build_configuration }}\XBrackets.dll
